/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siakad.form;

import siakad.dao.NilaiDao;
import siakad.entity.Nilai;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asrippdga
 */
public class FormNilai extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    /**
     * Creates new form FormNilai
     */
    public FormNilai() {
        initComponents();
        
         //Siapkan table model untuk JTable
        String[] namaKolom = new String[]{
            "NIM","Tanggal Lulus","IPK","Predikat"
        };
        int jumlahBarisAwal = 0; // Jumlah baris awal
        
        //membuat table model
        this.tableModel = new DefaultTableModel(namaKolom, jumlahBarisAwal);
        
        //menghubungkan mmodel dengan tablenya
        this.tblNilai.setModel(this.tableModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNilai = new javax.swing.JTable();
        lblNim = new javax.swing.JLabel();
        btnTampilkan = new javax.swing.JButton();
        lblTglLls = new javax.swing.JLabel();
        lblIpk = new javax.swing.JLabel();
        lblPredikat = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        txtTanggalLulus = new javax.swing.JTextField();
        txtIpk = new javax.swing.JTextField();
        txtPredikat = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNilai);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 440, 94));

        lblNim.setText("NIM :");
        getContentPane().add(lblNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 10));

        btnTampilkan.setText("tampilkan");
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });
        getContentPane().add(btnTampilkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        lblTglLls.setText("Tanggal Lulus : ");
        getContentPane().add(lblTglLls, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblIpk.setText("IPK : ");
        getContentPane().add(lblIpk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lblPredikat.setText("Predikat : ");
        getContentPane().add(lblPredikat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        getContentPane().add(txtNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 200, -1));
        getContentPane().add(txtTanggalLulus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 200, -1));
        getContentPane().add(txtIpk, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 200, -1));
        getContentPane().add(txtPredikat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 200, -1));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        jLabel2.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        jLabel2.setText("Ijazah Mahasiswa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 530, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        // TODO add your handling code here:
        try {
            NilaiDao nd = new NilaiDao();
            ArrayList<Nilai> nilaiTerpilih = nd.selectAll();
            
            for(Nilai n : nilaiTerpilih){
                Object[] baris = new Object[]{
                    n.getNim(), n.getTanggal_lulus(), n.getIpk(), n.getPredikat()
                };
                this.tableModel.addRow(baris);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
       Integer nim = Integer.parseInt(this.txtNim.getText());
        String tanggal_lulus = this.txtTanggalLulus.getText();
        Double ipk = Double.parseDouble(this.txtIpk.getText());
        String predikat = this.txtPredikat.getText();
        
        System.out.println("SUKSES");
        
        //membuat entity baru dari nilai nilai yang didapat
        Nilai nilaiBaru = new Nilai();
        nilaiBaru.setNim(nim);
        nilaiBaru.setTanggal_lulus(tanggal_lulus);
        nilaiBaru.setIpk(ipk);
        nilaiBaru.setPredikat(predikat);
        
        //Memanggil DAO
        NilaiDao nd = new NilaiDao(); 
        nd.insertOne(nilaiBaru);
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        txtNim.setText("");
        txtTanggalLulus.setText("");
        txtIpk.setText("");
        txtPredikat.setText("");
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIpk;
    private javax.swing.JLabel lblNim;
    private javax.swing.JLabel lblPredikat;
    private javax.swing.JLabel lblTglLls;
    private javax.swing.JTable tblNilai;
    private javax.swing.JTextField txtIpk;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtPredikat;
    private javax.swing.JTextField txtTanggalLulus;
    // End of variables declaration//GEN-END:variables
}
